[project]
name = "qa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.13.0",
    "datasets>=4.8.5",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
    "openai>=2.40.0",
    "ragas>=0.4.3",
    "rank-bm25>=0.2.2",
    "scikit-learn>=1.9.0",
    "sentence-transformers>=5.5.1",
    "tenacity>=9.1.4",
    "tinygrad>=0.13.0",
    "wandb>=0.27.0",
]
